<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Customer Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            font-size: 22px;
            color: #2c3e50;
        }
        .company-info {
            text-align: center;
            margin-bottom: 20px;
        }
        .report-info {
            margin-bottom: 20px;
        }
        .report-info table {
            width: 100%;
        }
        .report-info td {
            padding: 3px 0;
        }
        .summary-box {
            background-color: #f8f9fa;
            border: 1px solid #ddd;
            border-radius: 5px;
            padding: 10px;
            margin-bottom: 20px;
        }
        .summary-box h3 {
            margin-top: 0;
            font-size: 14px;
            border-bottom: 1px solid #ddd;
            padding-bottom: 5px;
            margin-bottom: 10px;
        }
        .summary-row {
            display: flex;
            justify-content: space-between;
            margin-bottom: 5px;
        }
        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        table.data-table th, 
        table.data-table td {
            border: 1px solid #ddd;
            padding: 5px;
            text-align: left;
            font-size: 10px;
        }
        table.data-table th {
            background-color: #f8f9fa;
            font-weight: bold;
        }
        .text-right {
            text-align: right;
        }
        .footer {
            text-align: center;
            margin-top: 30px;
            font-size: 10px;
            color: #777;
        }
        .page-break {
            page-break-after: always;
        }
        .badge {
            display: inline-block;
            padding: 2px 4px;
            font-size: 9px;
            font-weight: bold;
            border-radius: 3px;
        }
        .badge-success {
            background-color: #dff0d8;
            color: #3c763d;
        }
        .badge-warning {
            background-color: #fcf8e3;
            color: #8a6d3b;
        }
        .badge-danger {
            background-color: #f2dede;
            color: #a94442;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Customer Report</h1>
    </div>

    <div class="company-info">
        <strong>{{ config('app.name', 'Stock Management System') }}</strong><br>
        {{ date('F d, Y H:i:s') }}
    </div>

    <div class="report-info">
        <table>
            <tr>
                <td width="20%"><strong>Report Period:</strong></td>
                <td>{{ $start_date->format('M d, Y') }} - {{ $end_date->format('M d, Y') }}</td>
                <td width="20%"><strong>Total Customers:</strong></td>
                <td width="25%">{{ $total_customers }}</td>
            </tr>
            <tr>
                <td><strong>Generated By:</strong></td>
                <td>{{ auth()->user()->name }}</td>
                <td><strong>Generated On:</strong></td>
                <td>{{ now()->format('M d, Y H:i') }}</td>
            </tr>
        </table>
    </div>

    <div class="summary-box">
        <h3>Customer Summary</h3>
        <div class="summary-row">
            <span><strong>Total Customers:</strong></span>
            <span>{{ $total_customers }}</span>
        </div>
        <div class="summary-row">
            <span><strong>Total Sales:</strong></span>
            <span>${{ number_format($total_sales, 2) }}</span>
        </div>
        <div class="summary-row">
            <span><strong>Total Due:</strong></span>
            <span>${{ number_format($total_due, 2) }}</span>
        </div>
        <div class="summary-row">
            <span><strong>Avg. Purchase per Customer:</strong></span>
            <span>${{ number_format($average_purchase, 2) }}</span>
        </div>
    </div>

    @if(isset($customers) && $customers->count() > 0)
    <h3>Customer List</h3>
    <table class="data-table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Total Orders</th>
                <th>Total Amount</th>
                <th>Total Due</th>
                <th>Last Purchase</th>
            </tr>
        </thead>
        <tbody>
            @foreach($customers as $customer)
            <tr>
                <td>{{ $customer->id }}</td>
                <td>{{ $customer->name }}</td>
                <td>{{ $customer->email ?? 'N/A' }}</td>
                <td>{{ $customer->phone ?? 'N/A' }}</td>
                <td class="text-right">{{ $customer->sales_count ?? 0 }}</td>
                <td class="text-right">${{ number_format($customer->total_sales ?? 0, 2) }}</td>
                <td class="text-right">${{ number_format($customer->total_due ?? 0, 2) }}</td>
                <td>{{ $customer->last_purchase_date ? $customer->last_purchase_date->format('M d, Y') : 'N/A' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @endif

    @if(isset($top_customers) && $top_customers->count() > 0)
    <h3>Top Customers</h3>
    <table class="data-table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Total Orders</th>
                <th>Total Amount</th>
                <th>% of Sales</th>
            </tr>
        </thead>
        <tbody>
            @foreach($top_customers as $customer)
            <tr>
                <td>{{ $customer->name }}</td>
                <td>{{ $customer->email ?? 'N/A' }}</td>
                <td>{{ $customer->phone ?? 'N/A' }}</td>
                <td class="text-right">{{ $customer->sales_count ?? 0 }}</td>
                <td class="text-right">${{ number_format($customer->total_sales ?? 0, 2) }}</td>
                <td class="text-right">{{ number_format($customer->percentage_of_sales ?? 0, 2) }}%</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @endif

    <div class="footer">
        <p>This report was generated on {{ now()->format('F d, Y H:i:s') }}</p>
        <p>{{ config('app.name', 'Stock Management System') }} &copy; {{ date('Y') }}</p>
    </div>
</body>
</html> 