<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Product Expiry Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            color: #333;
            font-size: 22px;
            margin: 0;
            padding: 0;
        }
        .company-info {
            text-align: center;
            margin-bottom: 30px;
            font-size: 14px;
        }
        .report-info {
            margin-bottom: 20px;
            border: 1px solid #ddd;
            padding: 10px;
            background-color: #f9f9f9;
        }
        .report-info table {
            width: 100%;
            border-collapse: collapse;
        }
        .report-info table td {
            padding: 5px;
            vertical-align: top;
        }
        .summary-box {
            margin-bottom: 20px;
            border: 1px solid #ddd;
            padding: 10px;
            background-color: #f9f9f9;
        }
        .summary-box h3 {
            margin-top: 0;
            font-size: 14px;
            color: #333;
        }
        .summary-box table {
            width: 100%;
            border-collapse: collapse;
        }
        .summary-box table td {
            padding: 5px;
            vertical-align: top;
        }
        .summary-box .expired {
            color: #d9534f;
            font-weight: bold;
        }
        .summary-box .warning {
            color: #f0ad4e;
            font-weight: bold;
        }
        .summary-box .info {
            color: #5bc0de;
            font-weight: bold;
        }
        .data-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        .data-table th {
            background-color: #f5f5f5;
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
            font-size: 12px;
        }
        .data-table td {
            border: 1px solid #ddd;
            padding: 8px;
            font-size: 11px;
        }
        .data-table tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .text-right {
            text-align: right;
        }
        .footer {
            text-align: center;
            margin-top: 30px;
            font-size: 10px;
            color: #777;
        }
        .page-break {
            page-break-after: always;
        }
        .badge {
            display: inline-block;
            padding: 2px 4px;
            font-size: 9px;
            font-weight: bold;
            border-radius: 3px;
        }
        .badge-success {
            background-color: #dff0d8;
            color: #3c763d;
        }
        .badge-info {
            background-color: #d9edf7;
            color: #31708f;
        }
        .badge-warning {
            background-color: #fcf8e3;
            color: #8a6d3b;
        }
        .badge-danger {
            background-color: #f2dede;
            color: #a94442;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Product Expiry Report</h1>
    </div>

    <div class="company-info">
        <strong>{{ config('app.name', 'Stock Management System') }}</strong><br>
        {{ date('F d, Y H:i:s') }}
    </div>

    <div class="report-info">
        <table>
            <tr>
                <td width="20%"><strong>Report Title:</strong></td>
                <td>{{ $title }}</td>
                <td width="20%"><strong>Total Products:</strong></td>
                <td width="25%">{{ $total_products }}</td>
            </tr>
            <tr>
                <td><strong>Generated By:</strong></td>
                <td>{{ auth()->user()->name }}</td>
                <td><strong>Generated On:</strong></td>
                <td>{{ now()->format('M d, Y H:i') }}</td>
            </tr>
            <tr>
                <td><strong>Report ID:</strong></td>
                <td>{{ $report->id ?? 'N/A' }}</td>
            </tr>
        </table>
    </div>

    <div class="summary-box">
        <h3>Expiry Summary</h3>
        <table>
            <tr>
                <td width="25%"><strong>Total Products:</strong></td>
                <td>{{ $total_products }}</td>
                <td width="25%"><strong>Total Value:</strong></td>
                <td>${{ number_format($total_value, 2) }}</td>
            </tr>
            <tr>
                <td><strong class="expired">Expired Products:</strong></td>
                <td>{{ $grouped_products['expired']->count() }} products ({{ $group_quantities['expired'] }} units)</td>
                <td><strong class="expired">Value of Expired:</strong></td>
                <td>${{ number_format($group_values['expired'], 2) }}</td>
            </tr>
            <tr>
                <td><strong class="warning">Expiring in 7 Days:</strong></td>
                <td>{{ $grouped_products['within_7_days']->count() }} products ({{ $group_quantities['within_7_days'] }} units)</td>
                <td><strong class="warning">Value at Risk (7 Days):</strong></td>
                <td>${{ number_format($group_values['within_7_days'], 2) }}</td>
            </tr>
            <tr>
                <td><strong class="info">Expiring in 30 Days:</strong></td>
                <td>{{ $grouped_products['within_30_days']->count() }} products ({{ $group_quantities['within_30_days'] }} units)</td>
                <td><strong class="info">Value at Risk (30 Days):</strong></td>
                <td>${{ number_format($group_values['within_30_days'], 2) }}</td>
            </tr>
        </table>
    </div>

    @if($grouped_products['expired']->count() > 0)
    <h3>Expired Products</h3>
    <table class="data-table">
        <thead>
            <tr>
                <th>Code</th>
                <th>Name</th>
                <th>Category</th>
                <th>Supplier</th>
                <th>Stock</th>
                <th>Cost</th>
                <th>Value</th>
                <th>Expiry Date</th>
                <th>Expired By</th>
            </tr>
        </thead>
        <tbody>
            @foreach($grouped_products['expired'] as $product)
            <tr>
                <td>{{ $product->code }}</td>
                <td>{{ $product->name }}</td>
                <td>{{ $product->category->name ?? 'N/A' }}</td>
                <td>{{ $product->supplier->name ?? 'N/A' }}</td>
                <td class="text-right">
                    {{ $product->current_stock }} {{ $product->unit }}
                    @if($product->current_stock <= 0)
                        <span class="badge badge-danger">Out</span>
                    @elseif($product->current_stock <= $product->min_stock)
                        <span class="badge badge-warning">Low</span>
                    @endif
                </td>
                <td class="text-right">${{ number_format($product->cost_price, 2) }}</td>
                <td class="text-right">${{ number_format($product->current_stock * $product->cost_price, 2) }}</td>
                <td>{{ $product->expiry_date->format('M d, Y') }}</td>
                <td>{{ $product->expiry_date->diffInDays(now(), false) * -1 }} days</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @endif

    @if($grouped_products['within_7_days']->count() > 0)
    <h3>Products Expiring Within 7 Days</h3>
    <table class="data-table">
        <thead>
            <tr>
                <th>Code</th>
                <th>Name</th>
                <th>Category</th>
                <th>Supplier</th>
                <th>Stock</th>
                <th>Cost</th>
                <th>Value</th>
                <th>Expiry Date</th>
                <th>Days Left</th>
            </tr>
        </thead>
        <tbody>
            @foreach($grouped_products['within_7_days'] as $product)
            <tr>
                <td>{{ $product->code }}</td>
                <td>{{ $product->name }}</td>
                <td>{{ $product->category->name ?? 'N/A' }}</td>
                <td>{{ $product->supplier->name ?? 'N/A' }}</td>
                <td class="text-right">
                    {{ $product->current_stock }} {{ $product->unit }}
                    @if($product->current_stock <= 0)
                        <span class="badge badge-danger">Out</span>
                    @elseif($product->current_stock <= $product->min_stock)
                        <span class="badge badge-warning">Low</span>
                    @endif
                </td>
                <td class="text-right">${{ number_format($product->cost_price, 2) }}</td>
                <td class="text-right">${{ number_format($product->current_stock * $product->cost_price, 2) }}</td>
                <td>{{ $product->expiry_date->format('M d, Y') }}</td>
                <td>{{ $product->expiry_date->diffInDays(now()) }} days</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @endif

    @if($products->count() > $grouped_products['expired']->count() + $grouped_products['within_7_days']->count())
    <h3>All Expiring Products</h3>
    <table class="data-table">
        <thead>
            <tr>
                <th>Code</th>
                <th>Name</th>
                <th>Category</th>
                <th>Supplier</th>
                <th>Stock</th>
                <th>Expiry Date</th>
                <th>Days Left</th>
                <th>Value</th>
            </tr>
        </thead>
        <tbody>
            @foreach($products as $product)
            @php
                $daysLeft = $product->expiry_date->diffInDays(now(), false);
                if ($daysLeft <= -1 || $daysLeft <= 7) continue; // Skip already shown products
            @endphp
            <tr>
                <td>{{ $product->code }}</td>
                <td>{{ $product->name }}</td>
                <td>{{ $product->category->name ?? 'N/A' }}</td>
                <td>{{ $product->supplier->name ?? 'N/A' }}</td>
                <td class="text-right">{{ $product->current_stock }} {{ $product->unit }}</td>
                <td>{{ $product->expiry_date->format('M d, Y') }}</td>
                <td>
                    @if($daysLeft < 0)
                        <span class="badge badge-danger">Expired</span>
                    @elseif($daysLeft <= 7)
                        <span class="badge badge-warning">{{ $daysLeft }} days</span>
                    @elseif($daysLeft <= 30)
                        <span class="badge badge-info">{{ $daysLeft }} days</span>
                    @else
                        <span class="badge badge-success">{{ $daysLeft }} days</span>
                    @endif
                </td>
                <td class="text-right">${{ number_format($product->current_stock * $product->cost_price, 2) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @endif

    <div class="footer">
        <p>This report was generated on {{ now()->format('F d, Y H:i:s') }}</p>
        <p>{{ config('app.name', 'Stock Management System') }} &copy; {{ date('Y') }}</p>
    </div>
</body>
</html> 