@extends('layouts.app')
@section('title', 'Expiry Report')
@section('content')
<div class="container-fluid">
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Expiry Report</h1>
        <div>
            <a href="{{ route('reports.index') }}" class="d-none d-sm-inline-block btn btn-sm btn-secondary shadow-sm">
                <i class="fas fa-arrow-left fa-sm text-white-50"></i> Back to Reports
            </a>
            @if(isset($report) && $report)
            <a href="{{ route('reports.download', $report->id) }}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
                <i class="fas fa-download fa-sm text-white-50"></i> Generate PDF
            </a>
            @endif
        </div>
    </div>

    <div class="row">
        <div class="col-xl-12 col-lg-12">
            <div class="card shadow mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Expiry Report</h6>
                </div>
                <div class="card-body">
                    <div class="row mb-4">
                        <div class="col-md-6">
                            <h6>Report Information</h6>
                            <table class="table table-sm table-borderless">
                                <tr>
                                    <td width="30%"><strong>Report Title:</strong></td>
                                    <td>{{ $title }}</td>
                                </tr>
                                <tr>
                                    <td><strong>Generated By:</strong></td>
                                    <td>{{ auth()->user()->name }}</td>
                                </tr>
                                <tr>
                                    <td><strong>Generated On:</strong></td>
                                    <td>{{ now()->format('M d, Y H:i') }}</td>
                                </tr>
                                @if($report)
                                <tr>
                                    <td><strong>Report ID:</strong></td>
                                    <td>{{ $report->id }}</td>
                                </tr>
                                @endif
                            </table>
                        </div>
                        <div class="col-md-6">
                            <h6>Filter Options</h6>
                            <form method="POST" action="{{ route('reports.generate') }}" class="form-inline">
                                @csrf
                                <input type="hidden" name="type" value="expiry">
                                <div class="form-group mb-2 mr-2">
                                    <label for="expiry_range" class="mr-2">Expiry Range:</label>
                                    <select name="expiry_range" id="expiry_range" class="form-control form-control-sm">
                                        <option value="expired" {{ $expiry_range == 'expired' ? 'selected' : '' }}>Expired</option>
                                        <option value="7_days" {{ $expiry_range == '7_days' ? 'selected' : '' }}>Within 7 Days</option>
                                        <option value="30_days" {{ $expiry_range == '30_days' ? 'selected' : '' }}>Within 30 Days</option>
                                        <option value="90_days" {{ $expiry_range == '90_days' ? 'selected' : '' }}>Within 90 Days</option>
                                        <option value="custom" {{ $expiry_range == 'custom' ? 'selected' : '' }}>Custom</option>
                                    </select>
                                </div>
                                <div class="form-group mb-2 mr-2" id="custom_days_container" style="{{ $expiry_range == 'custom' ? '' : 'display: none;' }}">
                                    <label for="days" class="mr-2">Days:</label>
                                    <input type="number" name="days" id="days" class="form-control form-control-sm" value="{{ $days }}" min="1" max="365">
                                </div>
                                <div class="form-group mb-2 mr-2">
                                    <label for="category_id" class="mr-2">Category:</label>
                                    <select name="category_id" id="category_id" class="form-control form-control-sm">
                                        <option value="">All Categories</option>
                                        @foreach($categories as $category)
                                            <option value="{{ $category->id }}" {{ $category_id == $category->id ? 'selected' : '' }}>{{ $category->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="form-group mb-2 mr-2">
                                    <label for="supplier_id" class="mr-2">Supplier:</label>
                                    <select name="supplier_id" id="supplier_id" class="form-control form-control-sm">
                                        <option value="">All Suppliers</option>
                                        @foreach($suppliers as $supplier)
                                            <option value="{{ $supplier->id }}" {{ $supplier_id == $supplier->id ? 'selected' : '' }}>{{ $supplier->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <button type="submit" class="btn btn-primary btn-sm mb-2">Apply Filters</button>
                            </form>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <!-- Summary Cards -->
                            <div class="row mb-4">
                                <div class="col-xl-3 col-md-6 mb-4">
                                    <div class="card border-left-danger shadow h-100 py-2">
                                        <div class="card-body">
                                            <div class="row no-gutters align-items-center">
                                                <div class="col mr-2">
                                                    <div class="text-xs font-weight-bold text-danger text-uppercase mb-1">Expired Products</div>
                                                    <div class="h5 mb-0 font-weight-bold text-gray-800">{{ $grouped_products['expired']->count() }}</div>
                                                    <div class="small text-muted">{{ $group_quantities['expired'] }} units ({{ number_format($group_values['expired'], 2) }})</div>
                                                </div>
                                                <div class="col-auto">
                                                    <i class="fas fa-calendar-times fa-2x text-gray-300"></i>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-3 col-md-6 mb-4">
                                    <div class="card border-left-warning shadow h-100 py-2">
                                        <div class="card-body">
                                            <div class="row no-gutters align-items-center">
                                                <div class="col mr-2">
                                                    <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Expiring Within 7 Days</div>
                                                    <div class="h5 mb-0 font-weight-bold text-gray-800">{{ $grouped_products['within_7_days']->count() }}</div>
                                                    <div class="small text-muted">{{ $group_quantities['within_7_days'] }} units ({{ number_format($group_values['within_7_days'], 2) }})</div>
                                                </div>
                                                <div class="col-auto">
                                                    <i class="fas fa-exclamation-triangle fa-2x text-gray-300"></i>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-3 col-md-6 mb-4">
                                    <div class="card border-left-info shadow h-100 py-2">
                                        <div class="card-body">
                                            <div class="row no-gutters align-items-center">
                                                <div class="col mr-2">
                                                    <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Expiring Within 30 Days</div>
                                                    <div class="h5 mb-0 font-weight-bold text-gray-800">{{ $grouped_products['within_30_days']->count() }}</div>
                                                    <div class="small text-muted">{{ $group_quantities['within_30_days'] }} units ({{ number_format($group_values['within_30_days'], 2) }})</div>
                                                </div>
                                                <div class="col-auto">
                                                    <i class="fas fa-calendar-day fa-2x text-gray-300"></i>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xl-3 col-md-6 mb-4">
                                    <div class="card border-left-success shadow h-100 py-2">
                                        <div class="card-body">
                                            <div class="row no-gutters align-items-center">
                                                <div class="col mr-2">
                                                    <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Total Expiring Products</div>
                                                    <div class="h5 mb-0 font-weight-bold text-gray-800">{{ $total_products }}</div>
                                                    <div class="small text-muted">Value: ${{ number_format($total_value, 2) }}</div>
                                                </div>
                                                <div class="col-auto">
                                                    <i class="fas fa-boxes fa-2x text-gray-300"></i>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            @if($products->count() > 0)
                            <div class="table-responsive">
                                <table class="table table-bordered table-striped" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>Product</th>
                                            <th>Code</th>
                                            <th>Category</th>
                                            <th>Supplier</th>
                                            <th>Stock</th>
                                            <th>Cost</th>
                                            <th>Value</th>
                                            <th>Expiry Date</th>
                                            <th>Days Left</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach($products as $product)
                                        <tr>
                                            <td>{{ $product->name }}</td>
                                            <td>{{ $product->code }}</td>
                                            <td>{{ $product->category->name ?? 'N/A' }}</td>
                                            <td>{{ $product->supplier->name ?? 'N/A' }}</td>
                                            <td>
                                                {{ $product->current_stock }} {{ $product->unit }}
                                                @if($product->current_stock <= 0)
                                                    <span class="badge badge-danger">Out</span>
                                                @elseif($product->current_stock <= $product->min_stock)
                                                    <span class="badge badge-warning">Low</span>
                                                @endif
                                            </td>
                                            <td>${{ number_format($product->cost_price, 2) }}</td>
                                            <td>${{ number_format($product->cost_price * $product->current_stock, 2) }}</td>
                                            <td>{{ $product->expiry_date->format('M d, Y') }}</td>
                                            <td>
                                                @php
                                                    $daysLeft = \Carbon\Carbon::now()->diffInDays($product->expiry_date, false);
                                                @endphp
                                                
                                                @if($daysLeft < 0)
                                                    <span class="badge badge-danger">Expired {{ abs($daysLeft) }} days ago</span>
                                                @elseif($daysLeft <= 7)
                                                    <span class="badge badge-warning">{{ $daysLeft }} days left</span>
                                                @elseif($daysLeft <= 30)
                                                    <span class="badge badge-info">{{ $daysLeft }} days left</span>
                                                @else
                                                    <span class="badge badge-success">{{ $daysLeft }} days left</span>
                                                @endif
                                            </td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                            @else
                            <div class="alert alert-info">
                                No products matching the selected criteria.
                            </div>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@push('scripts')
<script>
    $(document).ready(function() {
        $('#expiry_range').change(function() {
            if ($(this).val() === 'custom') {
                $('#custom_days_container').show();
            } else {
                $('#custom_days_container').hide();
            }
        });
    });
</script>
@endpush
@endsection 