<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Inventory Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            font-size: 22px;
            color: #2c3e50;
        }
        .company-info {
            text-align: center;
            margin-bottom: 20px;
        }
        .report-info {
            margin-bottom: 20px;
        }
        .report-info table {
            width: 100%;
        }
        .report-info td {
            padding: 3px 0;
        }
        .summary-box {
            background-color: #f8f9fa;
            border: 1px solid #ddd;
            border-radius: 5px;
            padding: 10px;
            margin-bottom: 20px;
        }
        .summary-box h3 {
            margin-top: 0;
            font-size: 14px;
            border-bottom: 1px solid #ddd;
            padding-bottom: 5px;
            margin-bottom: 10px;
        }
        .summary-row {
            display: flex;
            justify-content: space-between;
            margin-bottom: 5px;
        }
        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        table.data-table th, 
        table.data-table td {
            border: 1px solid #ddd;
            padding: 5px;
            text-align: left;
            font-size: 10px;
        }
        table.data-table th {
            background-color: #f8f9fa;
            font-weight: bold;
        }
        .text-right {
            text-align: right;
        }
        .footer {
            text-align: center;
            margin-top: 30px;
            font-size: 10px;
            color: #777;
        }
        .page-break {
            page-break-after: always;
        }
        .badge {
            display: inline-block;
            padding: 2px 4px;
            font-size: 9px;
            font-weight: bold;
            border-radius: 3px;
        }
        .badge-success {
            background-color: #dff0d8;
            color: #3c763d;
        }
        .badge-warning {
            background-color: #fcf8e3;
            color: #8a6d3b;
        }
        .badge-danger {
            background-color: #f2dede;
            color: #a94442;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Inventory Report</h1>
    </div>

    <div class="company-info">
        <strong>{{ config('app.name', 'Stock Management System') }}</strong><br>
        {{ date('F d, Y H:i:s') }}
    </div>

    <div class="report-info">
        <table>
            <tr>
                <td width="20%"><strong>Generated By:</strong></td>
                <td>{{ auth()->user()->name }}</td>
                <td width="20%"><strong>Total Products:</strong></td>
                <td width="25%">{{ $total_products }}</td>
            </tr>
            <tr>
                <td><strong>Generated On:</strong></td>
                <td>{{ now()->format('M d, Y H:i') }}</td>
                <td><strong>Report ID:</strong></td>
                <td>{{ $report->id ?? 'N/A' }}</td>
            </tr>
        </table>
    </div>

    <div class="summary-box">
        <h3>Inventory Summary</h3>
        <div class="summary-row">
            <span><strong>Total Inventory Value:</strong></span>
            <span>${{ number_format($total_inventory_value, 2) }}</span>
        </div>
        <div class="summary-row">
            <span><strong>Total Retail Value:</strong></span>
            <span>${{ number_format($total_retail_value, 2) }}</span>
        </div>
        <div class="summary-row">
            <span><strong>Potential Profit:</strong></span>
            <span>${{ number_format($potential_profit, 2) }}</span>
        </div>
        <div class="summary-row">
            <span><strong>Low Stock Items:</strong></span>
            <span>{{ $low_stock_count }}</span>
        </div>
        <div class="summary-row">
            <span><strong>Out of Stock Items:</strong></span>
            <span>{{ $out_of_stock_count }}</span>
        </div>
    </div>

    @if($products->count() > 0)
    <h3>Products List</h3>
    <table class="data-table">
        <thead>
            <tr>
                <th>Code</th>
                <th>Name</th>
                <th>Category</th>
                <th>Supplier</th>
                <th>Stock</th>
                <th>Cost</th>
                <th>Selling</th>
                <th>Value</th>
            </tr>
        </thead>
        <tbody>
            @foreach($products as $product)
            <tr>
                <td>{{ $product->code }}</td>
                <td>{{ $product->name }}</td>
                <td>{{ $product->category->name ?? 'N/A' }}</td>
                <td>{{ $product->supplier->name ?? 'N/A' }}</td>
                <td class="text-right">
                    {{ $product->current_stock }} {{ $product->unit }}
                    @if($product->current_stock <= 0)
                        <span class="badge badge-danger">Out</span>
                    @elseif($product->current_stock <= $product->min_stock)
                        <span class="badge badge-warning">Low</span>
                    @endif
                </td>
                <td class="text-right">${{ number_format($product->cost_price, 2) }}</td>
                <td class="text-right">${{ number_format($product->selling_price, 2) }}</td>
                <td class="text-right">${{ number_format($product->current_stock * $product->cost_price, 2) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @endif

    <div class="footer">
        <p>This report was generated on {{ now()->format('F d, Y H:i:s') }}</p>
        <p>{{ config('app.name', 'Stock Management System') }} &copy; {{ date('Y') }}</p>
    </div>
</body>
</html> 