@extends('layouts.app')

@section('title', 'Inventory Report')

@section('content')
<div class="container-fluid">
    <div class="row mb-4">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h5 class="mb-0">Inventory Report</h5>
                    <div>
                        <a href="{{ route('reports.download', $report->id) }}" class="btn btn-sm btn-success me-1">
                            <i class="fas fa-download me-1"></i> Download PDF
                        </a>
                        <a href="{{ route('reports.download-csv', $report->id) }}" class="btn btn-sm btn-primary me-1">
                            <i class="fas fa-file-csv me-1"></i> Download CSV
                        </a>
                        <a href="{{ route('reports.index') }}" class="btn btn-sm btn-secondary">
                            <i class="fas fa-arrow-left me-1"></i> Back to Reports
                        </a>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row mb-4">
                        <div class="col-md-6">
                            <h6>Report Information</h6>
                            <table class="table table-sm table-borderless">
                                <tr>
                                    <td width="30%"><strong>Generated By:</strong></td>
                                    <td>{{ auth()->user()->name }}</td>
                                </tr>
                                <tr>
                                    <td><strong>Generated On:</strong></td>
                                    <td>{{ now()->format('M d, Y H:i') }}</td>
                                </tr>
                                @if($report)
                                <tr>
                                    <td><strong>Report ID:</strong></td>
                                    <td>{{ $report->id }}</td>
                                </tr>
                                @endif
                            </table>
                        </div>
                        <div class="col-md-6">
                            <h6>Inventory Summary</h6>
                            <table class="table table-sm table-borderless">
                                <tr>
                                    <td width="50%"><strong>Total Products:</strong></td>
                                    <td>{{ $total_products }}</td>
                                </tr>
                                <tr>
                                    <td><strong>Total Inventory Value:</strong></td>
                                    <td>${{ number_format($total_inventory_value, 2) }}</td>
                                </tr>
                                <tr>
                                    <td><strong>Total Retail Value:</strong></td>
                                    <td>${{ number_format($total_retail_value, 2) }}</td>
                                </tr>
                                <tr>
                                    <td><strong>Potential Profit:</strong></td>
                                    <td>${{ number_format($potential_profit, 2) }}</td>
                                </tr>
                                <tr>
                                    <td><strong>Low Stock Items:</strong></td>
                                    <td>{{ $low_stock_count }}</td>
                                </tr>
                                <tr>
                                    <td><strong>Out of Stock Items:</strong></td>
                                    <td>{{ $out_of_stock_count }}</td>
                                </tr>
                            </table>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <h6>Products List</h6>
                            <div class="table-responsive">
                                <table class="table table-bordered table-striped">
                                    <thead>
                                        <tr>
                                            <th>Code</th>
                                            <th>Name</th>
                                            <th>Category</th>
                                            <th>Supplier</th>
                                            <th>Stock</th>
                                            <th>Cost</th>
                                            <th>Selling</th>
                                            <th>Value</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach($products as $product)
                                        <tr>
                                            <td>{{ $product->code }}</td>
                                            <td>{{ $product->name }}</td>
                                            <td>{{ $product->category->name ?? 'N/A' }}</td>
                                            <td>{{ $product->supplier->name ?? 'N/A' }}</td>
                                            <td class="text-end">
                                                {{ $product->current_stock }} {{ $product->unit }}
                                                @if($product->current_stock <= 0)
                                                    <span class="badge bg-danger">Out</span>
                                                @elseif($product->current_stock <= $product->min_stock)
                                                    <span class="badge bg-warning text-dark">Low</span>
                                                @endif
                                            </td>
                                            <td class="text-end">${{ number_format($product->cost_price, 2) }}</td>
                                            <td class="text-end">${{ number_format($product->selling_price, 2) }}</td>
                                            <td class="text-end">${{ number_format($product->current_stock * $product->cost_price, 2) }}</td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection 