<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Profit and Loss Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            font-size: 22px;
            color: #2c3e50;
        }
        .company-info {
            text-align: center;
            margin-bottom: 20px;
        }
        .report-info {
            margin-bottom: 20px;
        }
        .report-info table {
            width: 100%;
        }
        .report-info td {
            padding: 3px 0;
        }
        .summary-box {
            background-color: #f8f9fa;
            border: 1px solid #ddd;
            border-radius: 5px;
            padding: 10px;
            margin-bottom: 20px;
        }
        .summary-box h3 {
            margin-top: 0;
            font-size: 14px;
            border-bottom: 1px solid #ddd;
            padding-bottom: 5px;
            margin-bottom: 10px;
        }
        .summary-row {
            display: flex;
            justify-content: space-between;
            margin-bottom: 5px;
        }
        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        table.data-table th, 
        table.data-table td {
            border: 1px solid #ddd;
            padding: 5px;
            text-align: left;
            font-size: 10px;
        }
        table.data-table th {
            background-color: #f8f9fa;
            font-weight: bold;
        }
        .text-right {
            text-align: right;
        }
        .footer {
            text-align: center;
            margin-top: 30px;
            font-size: 10px;
            color: #777;
        }
        .page-break {
            page-break-after: always;
        }
        .color-red {
            color: #dc3545;
        }
        .color-green {
            color: #28a745;
        }
        .section-title {
            background-color: #f8f9fa;
            padding: 5px;
            margin-top: 15px;
            margin-bottom: 10px;
            font-weight: bold;
            border-left: 3px solid #4e73df;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Profit and Loss Report</h1>
    </div>

    <div class="company-info">
        <strong>{{ config('app.name', 'Stock Management System') }}</strong><br>
        {{ date('F d, Y H:i:s') }}
    </div>

    <div class="report-info">
        <table>
            <tr>
                <td width="20%"><strong>Report Period:</strong></td>
                <td>{{ $start_date->format('M d, Y') }} - {{ $end_date->format('M d, Y') }}</td>
                <td width="20%"><strong>Generated By:</strong></td>
                <td width="25%">{{ auth()->user()->name }}</td>
            </tr>
            <tr>
                <td><strong>Report ID:</strong></td>
                <td>{{ $report->id ?? 'N/A' }}</td>
                <td><strong>Generated On:</strong></td>
                <td>{{ now()->format('M d, Y H:i') }}</td>
            </tr>
        </table>
    </div>

    <div class="summary-box">
        <h3>Profit & Loss Summary</h3>
        <div class="summary-row">
            <span><strong>Total Revenue:</strong></span>
            <span>${{ number_format($total_revenue, 2) }}</span>
        </div>
        <div class="summary-row">
            <span><strong>Cost of Goods Sold:</strong></span>
            <span>${{ number_format($cost_of_goods_sold, 2) }}</span>
        </div>
        <div class="summary-row">
            <span><strong>Gross Profit:</strong></span>
            <span>${{ number_format($gross_profit, 2) }}</span>
        </div>
        <div class="summary-row">
            <span><strong>Total Expenses:</strong></span>
            <span>${{ number_format($total_expenses, 2) }}</span>
        </div>
        <div class="summary-row">
            <span><strong>Net Profit:</strong></span>
            <span class="{{ $net_profit >= 0 ? 'color-green' : 'color-red' }}">
                ${{ number_format($net_profit, 2) }}
            </span>
        </div>
        <div class="summary-row">
            <span><strong>Profit Margin:</strong></span>
            <span class="{{ $profit_margin >= 0 ? 'color-green' : 'color-red' }}">
                {{ number_format($profit_margin, 2) }}%
            </span>
        </div>
    </div>

    <div class="section-title">Income</div>
    <table class="data-table">
        <thead>
            <tr>
                <th>Category</th>
                <th class="text-right">Amount</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Sales Revenue</td>
                <td class="text-right">${{ number_format($total_revenue, 2) }}</td>
            </tr>
            <!-- Add other income sources if available -->
            <tr>
                <td><strong>Total Income</strong></td>
                <td class="text-right"><strong>${{ number_format($total_revenue, 2) }}</strong></td>
            </tr>
        </tbody>
    </table>

    <div class="section-title">Cost of Goods Sold</div>
    <table class="data-table">
        <thead>
            <tr>
                <th>Category</th>
                <th class="text-right">Amount</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Cost of Goods Sold</td>
                <td class="text-right">${{ number_format($cost_of_goods_sold, 2) }}</td>
            </tr>
            <tr>
                <td><strong>Total Cost of Goods Sold</strong></td>
                <td class="text-right"><strong>${{ number_format($cost_of_goods_sold, 2) }}</strong></td>
            </tr>
        </tbody>
    </table>

    <div class="section-title">Expenses</div>
    <table class="data-table">
        <thead>
            <tr>
                <th>Category</th>
                <th class="text-right">Amount</th>
            </tr>
        </thead>
        <tbody>
            @if(count($expenses) > 0)
                @foreach($expenses as $category => $amount)
                <tr>
                    <td>{{ $category }}</td>
                    <td class="text-right">${{ number_format($amount, 2) }}</td>
                </tr>
                @endforeach
            @else
                <tr>
                    <td colspan="2" class="text-center">No expenses recorded for this period</td>
                </tr>
            @endif
            <tr>
                <td><strong>Total Expenses</strong></td>
                <td class="text-right"><strong>${{ number_format($total_expenses, 2) }}</strong></td>
            </tr>
        </tbody>
    </table>

    <div class="section-title">Monthly Performance</div>
    <table class="data-table">
        <thead>
            <tr>
                <th>Month</th>
                <th class="text-right">Revenue</th>
                <th class="text-right">Cost</th>
                <th class="text-right">Profit</th>
                <th class="text-right">Profit Margin</th>
            </tr>
        </thead>
        <tbody>
            @foreach($monthly_data as $month)
            <tr>
                <td>{{ $month['label'] }}</td>
                <td class="text-right">${{ number_format($month['revenue'], 2) }}</td>
                <td class="text-right">${{ number_format($month['cost'], 2) }}</td>
                <td class="text-right" class="{{ $month['profit'] >= 0 ? 'color-green' : 'color-red' }}">
                    ${{ number_format($month['profit'], 2) }}
                </td>
                <td class="text-right">
                    @if($month['revenue'] > 0)
                        {{ number_format(($month['profit'] / $month['revenue']) * 100, 2) }}%
                    @else
                        0.00%
                    @endif
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>This report was generated on {{ now()->format('F d, Y H:i:s') }}</p>
        <p>{{ config('app.name', 'Stock Management System') }} &copy; {{ date('Y') }}</p>
    </div>
</body>
</html> 