@extends('layouts.app')

@section('title', 'Profit and Loss Report')

@section('content')
<div class="container-fluid">
    <div class="row mb-4">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h5 class="mb-0">Profit and Loss Report</h5>
                    <div>
                        <a href="{{ route('reports.download', $report->id) }}" class="btn btn-sm btn-success">
                            <i class="fas fa-download me-1"></i> Download PDF
                        </a>
                        <a href="{{ route('reports.index') }}" class="btn btn-sm btn-secondary">
                            <i class="fas fa-arrow-left me-1"></i> Back to Reports
                        </a>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row mb-4">
                        <div class="col-md-6">
                            <h6>Report Information</h6>
                            <table class="table table-sm table-borderless">
                                <tr>
                                    <td width="30%"><strong>Report Period:</strong></td>
                                    <td>{{ $start_date->format('M d, Y') }} - {{ $end_date->format('M d, Y') }}</td>
                                </tr>
                                <tr>
                                    <td><strong>Generated By:</strong></td>
                                    <td>{{ auth()->user()->name }}</td>
                                </tr>
                                <tr>
                                    <td><strong>Generated On:</strong></td>
                                    <td>{{ now()->format('M d, Y H:i') }}</td>
                                </tr>
                                @if($report)
                                <tr>
                                    <td><strong>Report ID:</strong></td>
                                    <td>{{ $report->id }}</td>
                                </tr>
                                @endif
                            </table>
                        </div>
                        <div class="col-md-6">
                            <h6>Profit & Loss Summary</h6>
                            <table class="table table-sm table-borderless">
                                <tr>
                                    <td width="50%"><strong>Total Revenue:</strong></td>
                                    <td>${{ number_format($total_revenue, 2) }}</td>
                                </tr>
                                <tr>
                                    <td><strong>Cost of Goods Sold:</strong></td>
                                    <td>${{ number_format($cost_of_goods_sold, 2) }}</td>
                                </tr>
                                <tr>
                                    <td><strong>Gross Profit:</strong></td>
                                    <td>${{ number_format($gross_profit, 2) }}</td>
                                </tr>
                                <tr>
                                    <td><strong>Total Expenses:</strong></td>
                                    <td>${{ number_format($total_expenses, 2) }}</td>
                                </tr>
                                <tr>
                                    <td><strong>Net Profit:</strong></td>
                                    <td class="{{ $net_profit >= 0 ? 'text-success' : 'text-danger' }}">
                                        ${{ number_format($net_profit, 2) }}
                                    </td>
                                </tr>
                                <tr>
                                    <td><strong>Profit Margin:</strong></td>
                                    <td class="{{ $profit_margin >= 0 ? 'text-success' : 'text-danger' }}">
                                        {{ number_format($profit_margin, 2) }}%
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6 mb-4">
                            <div class="card">
                                <div class="card-header bg-light">
                                    <h6 class="mb-0">Income</h6>
                                </div>
                                <div class="card-body p-0">
                                    <table class="table table-bordered mb-0">
                                        <thead>
                                            <tr>
                                                <th>Category</th>
                                                <th class="text-end">Amount</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>Sales Revenue</td>
                                                <td class="text-end">${{ number_format($total_revenue, 2) }}</td>
                                            </tr>
                                            <!-- Add other income sources if available -->
                                            <tr class="table-light">
                                                <td><strong>Total Income</strong></td>
                                                <td class="text-end"><strong>${{ number_format($total_revenue, 2) }}</strong></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-6 mb-4">
                            <div class="card">
                                <div class="card-header bg-light">
                                    <h6 class="mb-0">Cost of Goods Sold</h6>
                                </div>
                                <div class="card-body p-0">
                                    <table class="table table-bordered mb-0">
                                        <thead>
                                            <tr>
                                                <th>Category</th>
                                                <th class="text-end">Amount</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>Cost of Goods Sold</td>
                                                <td class="text-end">${{ number_format($cost_of_goods_sold, 2) }}</td>
                                            </tr>
                                            <tr class="table-light">
                                                <td><strong>Total Cost of Goods Sold</strong></td>
                                                <td class="text-end"><strong>${{ number_format($cost_of_goods_sold, 2) }}</strong></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12 mb-4">
                            <div class="card">
                                <div class="card-header bg-light">
                                    <h6 class="mb-0">Expenses</h6>
                                </div>
                                <div class="card-body p-0">
                                    <table class="table table-bordered mb-0">
                                        <thead>
                                            <tr>
                                                <th>Category</th>
                                                <th class="text-end">Amount</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @if(count($expenses) > 0)
                                                @foreach($expenses as $category => $amount)
                                                <tr>
                                                    <td>{{ $category }}</td>
                                                    <td class="text-end">${{ number_format($amount, 2) }}</td>
                                                </tr>
                                                @endforeach
                                            @else
                                                <tr>
                                                    <td colspan="2" class="text-center">No expenses recorded for this period</td>
                                                </tr>
                                            @endif
                                            <tr class="table-light">
                                                <td><strong>Total Expenses</strong></td>
                                                <td class="text-end"><strong>${{ number_format($total_expenses, 2) }}</strong></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-header bg-light">
                                    <h6 class="mb-0">Monthly Performance</h6>
                                </div>
                                <div class="card-body p-0">
                                    <div class="table-responsive">
                                        <table class="table table-bordered mb-0">
                                            <thead>
                                                <tr>
                                                    <th>Month</th>
                                                    <th class="text-end">Revenue</th>
                                                    <th class="text-end">Cost</th>
                                                    <th class="text-end">Profit</th>
                                                    <th class="text-end">Profit Margin</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach($monthly_data as $month)
                                                <tr>
                                                    <td>{{ $month['label'] }}</td>
                                                    <td class="text-end">${{ number_format($month['revenue'], 2) }}</td>
                                                    <td class="text-end">${{ number_format($month['cost'], 2) }}</td>
                                                    <td class="text-end {{ $month['profit'] >= 0 ? 'text-success' : 'text-danger' }}">
                                                        ${{ number_format($month['profit'], 2) }}
                                                    </td>
                                                    <td class="text-end">
                                                        @if($month['revenue'] > 0)
                                                            {{ number_format(($month['profit'] / $month['revenue']) * 100, 2) }}%
                                                        @else
                                                            0.00%
                                                        @endif
                                                    </td>
                                                </tr>
                                                @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection 