@extends('layouts.app')

@section('title', 'Purchase Report')

@section('content')
<div class="container-fluid">
    <div class="row mb-4">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h5 class="mb-0">Purchase Report</h5>
                    <div>
                        <a href="{{ route('reports.download', $report->id) }}" class="btn btn-sm btn-success">
                            <i class="fas fa-download me-1"></i> Download PDF
                        </a>
                        <a href="{{ route('reports.index') }}" class="btn btn-sm btn-secondary">
                            <i class="fas fa-arrow-left me-1"></i> Back to Reports
                        </a>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row mb-4">
                        <div class="col-md-6">
                            <h6>Report Information</h6>
                            <table class="table table-sm table-borderless">
                                <tr>
                                    <td width="30%"><strong>Report Period:</strong></td>
                                    <td>{{ $start_date->format('M d, Y') }} - {{ $end_date->format('M d, Y') }}</td>
                                </tr>
                                <tr>
                                    <td><strong>Generated By:</strong></td>
                                    <td>{{ auth()->user()->name }}</td>
                                </tr>
                                <tr>
                                    <td><strong>Generated On:</strong></td>
                                    <td>{{ now()->format('M d, Y H:i') }}</td>
                                </tr>
                                @if($report)
                                <tr>
                                    <td><strong>Report ID:</strong></td>
                                    <td>{{ $report->id }}</td>
                                </tr>
                                @endif
                            </table>
                        </div>
                        <div class="col-md-6">
                            <h6>Purchase Summary</h6>
                            <table class="table table-sm table-borderless">
                                <tr>
                                    <td width="50%"><strong>Total Purchases:</strong></td>
                                    <td>{{ $total_purchases }}</td>
                                </tr>
                                <tr>
                                    <td><strong>Total Amount:</strong></td>
                                    <td>${{ number_format($total_amount, 2) }}</td>
                                </tr>
                                <tr>
                                    <td><strong>Total Paid:</strong></td>
                                    <td>${{ number_format($total_paid, 2) }}</td>
                                </tr>
                                <tr>
                                    <td><strong>Total Due:</strong></td>
                                    <td>${{ number_format($total_due, 2) }}</td>
                                </tr>
                            </table>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <h6>Purchase List</h6>
                            <div class="table-responsive">
                                <table class="table table-bordered table-striped">
                                    <thead>
                                        <tr>
                                            <th>Reference</th>
                                            <th>Date</th>
                                            <th>Supplier</th>
                                            <th>Amount</th>
                                            <th>Paid</th>
                                            <th>Due</th>
                                            <th>Status</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach($purchases as $purchase)
                                        <tr>
                                            <td>{{ $purchase->reference_no ?? 'N/A' }}</td>
                                            <td>{{ $purchase->date->format('M d, Y') }}</td>
                                            <td>{{ $purchase->supplier->name ?? 'N/A' }}</td>
                                            <td class="text-end">${{ number_format($purchase->total_amount, 2) }}</td>
                                            <td class="text-end">${{ number_format($purchase->paid_amount, 2) }}</td>
                                            <td class="text-end">${{ number_format($purchase->total_amount - $purchase->paid_amount, 2) }}</td>
                                            <td>
                                                @if($purchase->status == 'completed')
                                                    <span class="badge bg-success">Completed</span>
                                                @elseif($purchase->status == 'pending')
                                                    <span class="badge bg-warning text-dark">Pending</span>
                                                @else
                                                    <span class="badge bg-danger">{{ ucfirst($purchase->status) }}</span>
                                                @endif
                                            </td>
                                            <td>
                                                <a href="{{ route('purchases.show', $purchase->id) }}" class="btn btn-sm btn-info">
                                                    <i class="fas fa-eye"></i>
                                                </a>
                                            </td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection 