<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Sales Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            font-size: 22px;
            color: #2c3e50;
        }
        .company-info {
            text-align: center;
            margin-bottom: 20px;
        }
        .report-info {
            margin-bottom: 20px;
        }
        .report-info table {
            width: 100%;
        }
        .report-info td {
            padding: 3px 0;
        }
        .summary-box {
            background-color: #f8f9fa;
            border: 1px solid #ddd;
            border-radius: 5px;
            padding: 10px;
            margin-bottom: 20px;
        }
        .summary-box h3 {
            margin-top: 0;
            font-size: 14px;
            border-bottom: 1px solid #ddd;
            padding-bottom: 5px;
            margin-bottom: 10px;
        }
        .summary-row {
            display: flex;
            justify-content: space-between;
            margin-bottom: 5px;
        }
        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        table.data-table th, 
        table.data-table td {
            border: 1px solid #ddd;
            padding: 5px;
            text-align: left;
            font-size: 10px;
        }
        table.data-table th {
            background-color: #f8f9fa;
            font-weight: bold;
        }
        .text-right {
            text-align: right;
        }
        .footer {
            text-align: center;
            margin-top: 30px;
            font-size: 10px;
            color: #777;
        }
        .page-break {
            page-break-after: always;
        }
        .badge {
            display: inline-block;
            padding: 2px 4px;
            font-size: 9px;
            font-weight: bold;
            border-radius: 3px;
        }
        .badge-success {
            background-color: #dff0d8;
            color: #3c763d;
        }
        .badge-warning {
            background-color: #fcf8e3;
            color: #8a6d3b;
        }
        .badge-danger {
            background-color: #f2dede;
            color: #a94442;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Sales Report</h1>
    </div>

    <div class="company-info">
        <strong>{{ config('app.name', 'Stock Management System') }}</strong><br>
        {{ date('F d, Y H:i:s') }}
    </div>

    <div class="report-info">
        <table>
            <tr>
                <td width="20%"><strong>Report Period:</strong></td>
                <td>{{ $start_date->format('M d, Y') }} - {{ $end_date->format('M d, Y') }}</td>
                <td width="20%"><strong>Total Sales:</strong></td>
                <td width="25%">{{ $total_sales }}</td>
            </tr>
            <tr>
                <td><strong>Generated By:</strong></td>
                <td>{{ auth()->user()->name }}</td>
                <td><strong>Generated On:</strong></td>
                <td>{{ now()->format('M d, Y H:i') }}</td>
            </tr>
        </table>
    </div>

    <div class="summary-box">
        <h3>Sales Summary</h3>
        <div class="summary-row">
            <span><strong>Total Amount:</strong></span>
            <span>${{ number_format($total_amount, 2) }}</span>
        </div>
        <div class="summary-row">
            <span><strong>Total Paid:</strong></span>
            <span>${{ number_format($total_paid, 2) }}</span>
        </div>
        <div class="summary-row">
            <span><strong>Total Due:</strong></span>
            <span>${{ number_format($total_due, 2) }}</span>
        </div>
    </div>

    @if($sales->count() > 0)
    <h3>Sales List</h3>
    <table class="data-table">
        <thead>
            <tr>
                <th>Invoice</th>
                <th>Date</th>
                <th>Customer</th>
                <th>Amount</th>
                <th>Paid</th>
                <th>Due</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($sales as $sale)
            <tr>
                <td>{{ $sale->invoice_number }}</td>
                <td>{{ $sale->date->format('M d, Y') }}</td>
                <td>{{ $sale->customer->name ?? 'N/A' }}</td>
                <td class="text-right">${{ number_format($sale->total_amount, 2) }}</td>
                <td class="text-right">${{ number_format($sale->paid_amount, 2) }}</td>
                <td class="text-right">${{ number_format($sale->total_amount - $sale->paid_amount, 2) }}</td>
                <td>
                    @if($sale->status == 'completed')
                        <span class="badge badge-success">Completed</span>
                    @elseif($sale->status == 'pending')
                        <span class="badge badge-warning">Pending</span>
                    @else
                        <span class="badge badge-danger">{{ ucfirst($sale->status) }}</span>
                    @endif
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @endif

    @if(isset($product_sales) && count($product_sales) > 0)
    <h3>Top Selling Products</h3>
    <table class="data-table">
        <thead>
            <tr>
                <th>Product</th>
                <th>Quantity Sold</th>
                <th>Total Amount</th>
            </tr>
        </thead>
        <tbody>
            @foreach($product_sales as $id => $product)
            <tr>
                <td>{{ $product['name'] }}</td>
                <td class="text-right">{{ $product['quantity'] }}</td>
                <td class="text-right">${{ number_format($product['amount'], 2) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @endif

    <div class="footer">
        <p>This report was generated on {{ now()->format('F d, Y H:i:s') }}</p>
        <p>{{ config('app.name', 'Stock Management System') }} &copy; {{ date('Y') }}</p>
    </div>
</body>
</html> 