@extends('layouts.app')

@section('title', 'Sales Report')

@section('content')
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Sales Report</h1>
    <div>
        <a href="{{ route('reports.index') }}" class="btn btn-sm btn-secondary shadow-sm me-2">
            <i class="fas fa-arrow-left fa-sm text-white-50 me-1"></i> Back to Reports
        </a>
        <a href="{{ route('reports.generate', array_merge(request()->all(), ['pdf' => 1])) }}" class="btn btn-sm btn-primary shadow-sm me-2">
            <i class="fas fa-download fa-sm text-white-50 me-1"></i> Download PDF
        </a>
        <a href="{{ route('reports.generate', array_merge(request()->all(), ['csv' => 1])) }}" class="btn btn-sm btn-success shadow-sm">
            <i class="fas fa-file-csv fa-sm text-white-50 me-1"></i> Download CSV
        </a>
    </div>
</div>

<!-- Report Info Card -->
<div class="card shadow mb-4">
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Report Information</h6>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-3 mb-3">
                <strong>Report Period:</strong>
                <p>{{ $start_date->format('M d, Y') }} to {{ $end_date->format('M d, Y') }}</p>
            </div>
            <div class="col-md-3 mb-3">
                <strong>Total Sales:</strong>
                <p>${{ number_format($total_amount, 2) }}</p>
            </div>
            <div class="col-md-3 mb-3">
                <strong>Total Paid:</strong>
                <p>${{ number_format($total_paid, 2) }}</p>
            </div>
            <div class="col-md-3 mb-3">
                <strong>Total Due:</strong>
                <p>${{ number_format($total_due, 2) }}</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 mb-3">
                <strong>Generated At:</strong>
                <p>{{ $report->created_at->format('M d, Y g:i A') }}</p>
            </div>
            <div class="col-md-3 mb-3">
                <strong>Generated By:</strong>
                <p>{{ $report->user->name }}</p>
            </div>
            <div class="col-md-3 mb-3">
                <strong>Total Transactions:</strong>
                <p>{{ $total_sales }}</p>
            </div>
            <div class="col-md-3 mb-3">
                <strong>Filters Applied:</strong>
                <p>
                    @if(!empty($parameters['customer_id']))
                        <span class="badge bg-info">Customer: {{ \App\Models\Customer::find($parameters['customer_id'])->name }}</span>
                    @endif
                    @if(!empty($parameters['status']))
                        <span class="badge bg-info">Status: {{ ucfirst($parameters['status']) }}</span>
                    @endif
                    @if(!empty($parameters['payment_status']))
                        <span class="badge bg-info">Payment: {{ ucfirst($parameters['payment_status']) }}</span>
                    @endif
                </p>
            </div>
        </div>
    </div>
</div>

<!-- Sales Chart Card -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Sales Trend</h6>
    </div>
    <div class="card-body">
        <div class="chart-area">
            <canvas id="salesChart"></canvas>
        </div>
    </div>
</div>

<!-- Sales Table Card -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Sales Transactions</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Invoice</th>
                        <th>Customer</th>
                        <th>Items</th>
                        <th>Total</th>
                        <th>Paid</th>
                        <th>Due</th>
                        <th>Status</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($sales as $sale)
                        <tr>
                            <td>{{ $sale->date->format('M d, Y') }}</td>
                            <td>{{ $sale->invoice_number }}</td>
                            <td>{{ $sale->customer->name }}</td>
                            <td>{{ $sale->items->count() }}</td>
                            <td>${{ number_format($sale->total_amount, 2) }}</td>
                            <td>${{ number_format($sale->paid_amount, 2) }}</td>
                            <td>${{ number_format($sale->total_amount - $sale->paid_amount, 2) }}</td>
                            <td>
                                @if($sale->status == 'completed')
                                    <span class="badge bg-success">Completed</span>
                                @elseif($sale->status == 'pending')
                                    <span class="badge bg-warning">Pending</span>
                                @elseif($sale->status == 'canceled')
                                    <span class="badge bg-danger">Canceled</span>
                                @else
                                    <span class="badge bg-secondary">{{ ucfirst($sale->status) }}</span>
                                @endif
                            </td>
                            <td>
                                <a href="{{ route('sales.show', $sale->id) }}" class="btn btn-sm btn-primary">
                                    <i class="fas fa-eye"></i>
                                </a>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="9" class="text-center">No sales found for the selected period</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- Top Products & Customers -->
<div class="row">
    <!-- Top Products Card -->
    <div class="col-xl-6 col-lg-6">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Top Selling Products</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Product</th>
                                <th>Quantity Sold</th>
                                <th>Revenue</th>
                            </tr>
                        </thead>
                        <tbody>
                            @php
                                $topProducts = [];
                                foreach($sales as $sale) {
                                    foreach($sale->items as $item) {
                                        $productId = $item->product_id;
                                        $productName = $item->product->name;
                                        if (!isset($topProducts[$productId])) {
                                            $topProducts[$productId] = [
                                                'name' => $productName,
                                                'quantity' => 0,
                                                'revenue' => 0
                                            ];
                                        }
                                        $topProducts[$productId]['quantity'] += $item->quantity;
                                        $topProducts[$productId]['revenue'] += $item->total;
                                    }
                                }
                                
                                // Sort by revenue in descending order
                                uasort($topProducts, function($a, $b) {
                                    return $b['revenue'] <=> $a['revenue'];
                                });
                                
                                // Take top 10
                                $topProducts = array_slice($topProducts, 0, 10);
                            @endphp
                            
                            @forelse($topProducts as $productId => $product)
                                <tr>
                                    <td>{{ $product['name'] }}</td>
                                    <td>{{ $product['quantity'] }}</td>
                                    <td>${{ number_format($product['revenue'], 2) }}</td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="3" class="text-center">No product data available</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <!-- Top Customers Card -->
    <div class="col-xl-6 col-lg-6">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Top Customers</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Customer</th>
                                <th>Purchases</th>
                                <th>Total Spent</th>
                            </tr>
                        </thead>
                        <tbody>
                            @php
                                $topCustomers = [];
                                foreach($sales as $sale) {
                                    $customerId = $sale->customer_id;
                                    $customerName = $sale->customer->name;
                                    if (!isset($topCustomers[$customerId])) {
                                        $topCustomers[$customerId] = [
                                            'name' => $customerName,
                                            'purchases' => 0,
                                            'total' => 0
                                        ];
                                    }
                                    $topCustomers[$customerId]['purchases']++;
                                    $topCustomers[$customerId]['total'] += $sale->total_amount;
                                }
                                
                                // Sort by total spent in descending order
                                uasort($topCustomers, function($a, $b) {
                                    return $b['total'] <=> $a['total'];
                                });
                                
                                // Take top 10
                                $topCustomers = array_slice($topCustomers, 0, 10);
                            @endphp
                            
                            @forelse($topCustomers as $customerId => $customer)
                                <tr>
                                    <td>{{ $customer['name'] }}</td>
                                    <td>{{ $customer['purchases'] }}</td>
                                    <td>${{ number_format($customer['total'], 2) }}</td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="3" class="text-center">No customer data available</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        // Prepare chart data
        const salesData = @json($sales->groupBy(function($sale) {
            return $sale->date->format('Y-m-d');
        })->map(function($group) {
            return $group->sum('total_amount');
        }));
        
        const dates = Object.keys(salesData);
        const amounts = Object.values(salesData);
        
        // Create sales trend chart
        const ctx = document.getElementById('salesChart');
        if (ctx) {
            new Chart(ctx, {
                type: 'line',
                data: {
                    labels: dates.map(date => {
                        const d = new Date(date);
                        return d.toLocaleDateString();
                    }),
                    datasets: [{
                        label: 'Daily Sales',
                        lineTension: 0.3,
                        backgroundColor: "rgba(78, 115, 223, 0.05)",
                        borderColor: "rgba(78, 115, 223, 1)",
                        pointRadius: 3,
                        pointBackgroundColor: "rgba(78, 115, 223, 1)",
                        pointBorderColor: "rgba(78, 115, 223, 1)",
                        pointHoverRadius: 3,
                        pointHoverBackgroundColor: "rgba(78, 115, 223, 1)",
                        pointHoverBorderColor: "rgba(78, 115, 223, 1)",
                        pointHitRadius: 10,
                        pointBorderWidth: 2,
                        data: amounts,
                    }],
                },
                options: {
                    maintainAspectRatio: false,
                    layout: {
                        padding: {
                            left: 10,
                            right: 25,
                            top: 25,
                            bottom: 0
                        }
                    },
                    scales: {
                        x: {
                            time: {
                                unit: 'date'
                            },
                            grid: {
                                display: false,
                                drawBorder: false
                            },
                            ticks: {
                                maxTicksLimit: 7
                            }
                        },
                        y: {
                            ticks: {
                                maxTicksLimit: 5,
                                padding: 10,
                                callback: function(value, index, values) {
                                    return '$' + value.toFixed(2);
                                }
                            },
                            grid: {
                                color: "rgb(234, 236, 244)",
                                zeroLineColor: "rgb(234, 236, 244)",
                                drawBorder: false,
                                borderDash: [2],
                                zeroLineBorderDash: [2]
                            }
                        },
                    },
                    plugins: {
                        legend: {
                            display: false
                        },
                        tooltip: {
                            backgroundColor: "rgb(255,255,255)",
                            bodyColor: "#858796",
                            titleMarginBottom: 10,
                            titleColor: '#6e707e',
                            titleFontSize: 14,
                            borderColor: '#dddfeb',
                            borderWidth: 1,
                            xPadding: 15,
                            yPadding: 15,
                            displayColors: false,
                            intersect: false,
                            mode: 'index',
                            caretPadding: 10,
                            callbacks: {
                                label: function(context) {
                                    var label = context.dataset.label || '';
                                    if (label) {
                                        label += ': ';
                                    }
                                    if (context.parsed.y !== null) {
                                        label += '$' + context.parsed.y.toFixed(2);
                                    }
                                    return label;
                                }
                            }
                        }
                    }
                }
            });
        }
    });
</script>
@endsection

@section('styles')
<style>
    .chart-area {
        position: relative;
        height: 20rem;
        width: 100%;
    }
    
    .report-header {
        background-color: #f8f9fc;
    }
</style>
@endsection 